version: "3"

services:
  package:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: package
    restart: unless-stopped
    tty: true
    working_dir: /var/www/html
    environment:
      SERVICE_TAGS: dev
      SERVICE_NAME: package
    volumes:
      - ./:/var/www/html
    networks:
      - package-network

#Docker Networks
networks:
  package-network:
    driver: bridge